[package]
name = "fsrs-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.87"
getrandom = { version = "0.2", features = ["js"] }
web-sys = {version = "0.3.64", features = ["console"]}
console_error_panic_hook = "0.1.7"
console_log = { version = "0.2", features = ["color"] }
log = "0.4"

[dependencies.fsrs]
path = "../fsrs-rs"
# git = "https://github.com/open-spaced-repetition/fsrs-rs.git"
# rev = "aa797b950375d5f5be1cddacd5f9b85416fd8e0f"
# features = ["burn/wasm-sync"]

[dependencies.burn]
# version = "0.10.0"
# git = "https://github.com/burn-rs/burn.git"
# rev = "9f2bc599b880f069cc5f1ede21c69554adf3ee1e"
path = "../burn/burn/"
default-features = false
features = ["train-minimal", "autodiff", "dataset-minimal", "ndarray", "wasm-sync"]

[dependencies.libm]
version = "0.2.8"
